apiVersion: v1
kind: Service
metadata:
  name: simple-newapp-custom
spec:
  selector:
    deploymentconfig: simple-newapp
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080